api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    eager_loading:
        enabled: true
    collection:
    # global change parameter, but we changed in Entity
    #   order_parameter_name: '_order'
        pagination:
            #enabled: false
            page_parameter_name: _page
            #client_enabled: true
            #enabled_parameter_name: pagination
            items_per_page: 20
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 50
            partial: false
            client_partial: true
            partial_parameter_name: 'partial'
    exception_to_status:
        App\Exception\EmptyBodyException: 400
        App\Exception\InvalidConfirmationTokenException: 404

